id: IA6533CA3
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T14:13:26+00:00'
last_modified: '2022-06-08T09:32:43.378592+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4CZ16923
  title: 'མན་ངག་རྒྱུད། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    D7F3:
      image_group_id: I1KG13565
      title: ''
      total_pages: 422
      order: 1
      base_file: D7F3.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
