id: P006908
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 12:30:04.927365
source_metadata:
  id: bdr:W4CZ16923
  title: 'མན་ངག་རྒྱུད། '
  author: ''
  volumes:
    87367e580fc941debd8a4ff12ee3b4e1:
      image_group_id: I1KG13565
      title: ''
      volume_number: 1
      total_pages: 422
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
