id: P006908
initial_creation_type: ocr
source_metadata:
  id: bdr:W4CZ16923
  title: 'མན་ངག་རྒྱུད། '
  author: ''
  volumes:
    87367e580fc941debd8a4ff12ee3b4e1:
      image_group_id: I1KG13565
      title: ''
      volume_number: 1
      total_pages: 422
